TestParser
SABLEAN/cars-parser pull request #2
Opened 2021-11-19 11:25 UTC by SABLEAN

2021-11-21 06:11 UTC, SiberianPathfinder requested changes

2021-11-21 06:11 UTC, SiberianPathfinder commented on src/main/scala/Cars.scala
> +case class Cars(year: Int, brand: String, model: String)
Эта модель отражает данные одной машины, а название класса почему-то в множественном числе. Думаю, выгоднее было бы название `Car`, чтобы из-за названия диссонанс не вызывать

2021-11-21 06:11 UTC, SiberianPathfinder commented on src/main/scala/Cars2.scala
> +case class Cars2(car: String, years: List[Int])
Тож самое, что и с `Cars`

2021-11-21 06:11 UTC, SiberianPathfinder commented on src/main/scala/InOut.scala
> +  def intOut(l: List[String]): (String, String) = {
Сигнатура функции должна как можно очевиднее передавать смысл функции. По названию не совсем понятно, что будут парситься аргументы командной строки, и не будет понятно до тех пор, пока не посмотришь в тело функции. + `Tuple` тоже не совсем очевиден. Не понятно, где какой файл будет. Если смотреть только на возвращаемый тип, не понятно, где название исходного файла с данными, а где название результирующего файла. Вместо тюпла можно создать ещё одну модельку, например,` Arguments`, и поля в нём` fileNameIn` и `fileNameOut`

2021-11-21 06:11 UTC, SiberianPathfinder commented on src/main/scala/Parser.scala
> +    }
Можно, кстати, извлечь из этой функции ещё одну функцию `String => Cars`. Не обязательно. Но так будет легче с тестами. Можно отдельно протестить две логики: одна для парсинга машины из одной строки, другая для парсинга строк из csv

2021-11-21 06:11 UTC, SiberianPathfinder commented on src/test/scala/ParserTest.scala
> +      Parser.parser(List(("year,model,firma"),("1990,BMW,M3"))) shouldEqual List(Cars(1990,"BMW","M3"))
Скобочки))

2021-11-21 07:21 UTC, SABLEAN commented on src/main/scala/Cars.scala
> +case class Cars(year: Int, brand: String, model: String)
Исправил

2021-11-21 07:21 UTC, SABLEAN commented on src/main/scala/Cars2.scala
> +case class Cars2(car: String, years: List[Int])
Исправил

2021-11-21 07:22 UTC, SABLEAN commented on src/test/scala/ParserTest.scala
> +      Parser.parser(List(("year,model,firma"),("1990,BMW,M3"))) shouldEqual List(Cars(1990,"BMW","M3"))
Исправил

2021-11-21 12:37 UTC, SiberianPathfinder requested changes

2021-11-21 12:37 UTC, SiberianPathfinder commented on src/test/scala/CalculiatorTest.scala
> +      Calculiator.calculiator(List(Car(1990, "BMW", "M3"))) shouldEqual List(YearOfRelease("BMW M3", List(1990)))
На самом деле здесь напрашивается ещё один тест. По бизнес-логике программы, очень важно, чтобы для нескольких записей одной машины существовала одна результирующая запись с списком годов выпуска. На данный момент тесты не гарантируют такого кейса, так что лучше ещё один тест дописать.
Его можно дописать прям в этом же файле. Будет что-то похоже на следующее:
```scala
"Calculiator" should {

  "back List[YearOfRelease]" in {
    ???
  } 

  "do something else" in {
    ???
  "

  "do other stuff" in {
    ???
  }

}
```

2021-11-21 12:37 UTC, SiberianPathfinder commented on src/test/scala/UnparserTest.scala
> +      Unparser.unparser (List(YearOfRelease("BMW M3",List(1990)))) shouldEqual List("Car,Year", "BMW M3,[\"1990\"]")
Важно так-же проверить то, как функция будет записывать несколько годов. Чтобы для ```YearOfRelease("BMW M3", List(1990, 1992, 2000))``` была строка ```"BMW M3,[\"1990\", \"1992\", \"2000\"]"```

2021-11-22 12:06 UTC, SABLEAN commented on src/test/scala/CalculiatorTest.scala
> +      Calculiator.calculiator(List(Car(1990, "BMW", "M3"))) shouldEqual List(YearOfRelease("BMW M3", List(1990)))
Добавил

2021-11-22 12:46 UTC, SABLEAN commented on src/test/scala/UnparserTest.scala
> +      Unparser.unparser (List(YearOfRelease("BMW M3",List(1990)))) shouldEqual List("Car,Year", "BMW M3,[\"1990\"]")
Добавил

2021-11-23 14:01 UTC, SABLEAN commented on src/main/scala/InOut.scala
> +  def intOut(l: List[String]): (String, String) = {
Исправил

2021-11-23 14:14 UTC, SABLEAN commented on src/main/scala/Parser.scala
> +    }
Обновил

2021-11-23 14:25 UTC, SiberianPathfinder approved these changes
Good

2021-11-23 14:26 UTC, merged